In [3]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

1. keras.Functional 선형회귀경우

In [1]:
import keras

In [4]:
x = np.array(range(0,20))
y = x * 2 -1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [6]:
x.shape , y.shape
#  피쳐1개 data 20개

((20,), (20,))

In [7]:
# 이전 모델삭제
keras.backend.clear_session()

# Sequential 다르게 모델 선언전 input , output layer를 설정
# output layer 뒤에 input layer가 반드시 있어야함
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델선언 이전에 선언한 input, output 사용
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 선형 loss = mse
model.compile(loss = 'mse', optimizer = 'adam')


2. keras.Functional 분류(이진)경우

In [8]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [10]:
# 이전에 사용되었던 모델 삭제
keras.backend.clear_session()

# Sequential 다르게 모델 선언전 input , output layer를 설정
# output layer 뒤에 input layer가 반드시 있어야함
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)


# model 선언
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 이진 분류 loss = binary_crossentropy / 성능확인 보조지표로 accuracy 추가
model.compile(loss = 'binary_crossentropy',
              optimizer = 'adam',
              metrics=['accuracy'])

3. keras.Functional 분류(멀티클래스)경우

![iris_flower](https://www.embedded-robotics.com/wp-content/uploads/2022/01/Iris-Dataset-Classification-1024x367.png)

In [11]:
from sklearn.datasets import load_iris

In [12]:
iris = load_iris()

In [13]:
x = iris.data
y = iris.target

In [19]:
x.shape, y.shape

((150, 4), (150, 3))

In [14]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [16]:
# One-Hot Encoding y의 클래스 가변수화로 0,1로구분
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, 3)

In [18]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [20]:
# 이전에 사용되었던 모델 삭제
keras.backend.clear_session()

#  모델 블록 추가 피쳐수 4개, dense 3개있음
#  멀티 클래스경우 이전에 사용했던 시그모이드가 아닌 softmax 활용
#  시그모이드를 사용할 경우 예측값에 대한 총 합이 1이 되지않는 이슈발생

il = keras.layers.Input(shape=(4,))
ol = keras.layers.Dense(3, activation='softmax')(il)

#  모델선언
model= keras.models.Model(il, ol)

#  컴파일 멀티클래스 loss = categorical_crossentropy 사용
model.compile(loss='categorical_crossentropy',optimizer='adam')

In [ ]:
model.fit(x,y, epochs= 300 , verbose= 1 )